### ISSUE TITLE
Default build fails

### ISSUE THREAD

**Issue by popensesame** [azavea/lambda-geotrellis-tile-server#18]
The `publish` script takes three optional arguments which are then passed to `build-serverless`. If you don't supply any arguments, `publish` will pass empty strings to `build-serverless`, which interprets these as arguments instead of applying a default argument.

**Comment by jisantuc** [comment]
Thanks for the issue! I'll fix this up later this week

**Comment by popensesame** [comment]
Of course! Thanks for making this, it's super cool!

Another gotcha I'll just mention here: Serverless required the IAM user to have permissions from `aws:iam`, `aws:logs`, and `aws:s3` (I solved it by adding `"iam:*"`, `"logs:*"`, and `"s3:*"` permissions to the user policy).
